version: '2.2'
services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
      - 8080:8080
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
