FROM elasticsearch:7.5.0
MAINTAINER ARIES
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch repository-s3
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh", "elasticsearch"]
EXPOSE 9200 9300
